apiVersion: v1
kind: Service
metadata:
  name: model-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: designermodel
  ports:
    - name: inference
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: management
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: metrics
      protocol: TCP
      port: 8082
      targetPort: 8082

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: designermodel
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: designermodel
  template:
    metadata:
      labels:
        app: designermodel
    spec:
      terminationGracePeriodSeconds: 0
      hostname: designermodel
      nodeSelector:
        app: designermodel
      containers:
      - name: designermodel
        image: cr.yandex/crpbhviu3kh3io6cv5n0/sd
        imagePullPolicy: Always